name: Run Ensemble Model Notebook Script

on:
  push:
    branches:
      - main    
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  run-ensemble:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Ensemble Model script
      working-directory: notebooks
      run: python ensemble_model.py
